# Generated by Django 2.1.1 on 2020-09-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realtor',
            table='realtor',
        ),
    ]
